### ISSUE TITLE
Hello！An Example of Plant juice extraction ，have any idea？

### ISSUE THREAD

**Issue by libing403** [UgisL/flowMSE#1]
This model is Plant juice extraction as following figure。ADINA，ABAQUS ，fluent maybe have difficult to simulate the model ，How about FreeFem software？
Figure:[porous medium and a free fluid](https://github.com/libing403/LearningNotes/blob/master/Mechanics/FluidMechanics/porous%20medium%20and%20a%20free%20fluid.jpg)

**Comment by UgisL** [comment]
Dear libing403,

Thank you for your interest in FreeFEM++ and our solver. I have checked the drawing you are referring to. In general I think it should be possible, however, it would require significant effort put in development. Currently our model is suitable to describe only one-phase poroelastic problems, while you are aiming at two-phase problem. The current software is not suitable for such problem directly and I don't have time to develop it in that direction.

Therefore I close this issue, since the current solver is not designed for the problem in question.

Best of luck with your work.
Uģis

**Comment by libing403** [comment]
Dear Uģis，
       Thank you for your reply！I will search some papers to find the right way to solve this problem or do some development on the FreeFem++.
Best regards to you!
libing403
